server:
    port: 8090

spring:
    profiles: dev

    datasource:
         dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
         databaseName: hexa
         portNumber: 5432
         serverName: localhost
         username: postgres
         password: 12345678x@X

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 16M

# You can add as many as folders to watch
# You just need to add a dash + the directory to watch
hotReload:
    enabled: true
    package:
      project: com.yukam.mypam
      domain: com.yukam.mypam.domain
      restdto: com.yukam.mypam.web.rest.dto
    liquibase:
      defaultCatalogName: yukam
      defaultSchema: yukam
      excludeTables: 
    watchdir:
      - target/classes
